/*
 * AUTO-GENERATED FILE
 *
 * Do not edit this file manually.
 *
 * Generated by:
 *
 *   scripts/generateIdeaMetadata.ts
 */

import type {
  IdeaMetadata,
} from "./types";


export const generatedIdeaMetadata:
  IdeaMetadata[] = [
  {
    "id": "link",
    "name": "Link",
    "category": "Interaction",
    "type": "link",
    "description": "Create an interactive link that navigates to another URL.",
    "kind": "scene-object",
    "tags": [
      "link",
      "navigation",
      "button",
      "url",
      "interaction"
    ],
    "skills": [
      "interaction.link",
      "navigation.url"
    ],
    "schema": [
      {
        "name": "href",
        "type": "string",
        "required": true,
        "description": "The destination URL."
      },
      {
        "name": "text",
        "type": "string",
        "required": true,
        "description": "The visible text displayed on the link."
      }
    ]
  }
];
