/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import {
  AnimationMixer,
  Object3D,
} from "three";
import {
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from "react";
import {
  useGLTF,
} from "@react-three/drei";
import {
  GLTF,
} from "three-stdlib";
import {
  GroupProps,
  useFrame,
} from "@react-three/fiber";
import {
  SkeletonUtils,
} from "../utils/SkeletonUtils";


type GLTFResult = GLTF & {
  nodes: {
    avatar: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
    Armature: Object3D;
  };

  materials: {
    ["avatar.mat"]:
      THREE.MeshStandardMaterial;
  };
};


/* =========================================
   BUILDER ANIMATIONS
========================================= */

export type ActionName =
  | "swimmin"
  | "idle"
  | "lay"
  | "wave";


type GLTFActions =
  Record<
    ActionName,
    THREE.AnimationAction
  >;


const FILE_URL =
  "https://d27rt3a60hh1lx.cloudfront.net/models/SwimmingMort-1627646231/mort.glb.gz";


type ModelProps = {
  animation?: ActionName;

  duration?: number;
} & GroupProps;


export default function Model(
  props: ModelProps
) {

  const {
    animation = "idle",

    duration = 0.5,

    ...rest
  } = props;


  const {
    nodes,
    animations,
    materials,
  } =
    useGLTF(
      FILE_URL
    ) as GLTFResult;


  /* =========================================
     MATERIAL
  ========================================= */

  materials[
    "avatar.mat"
  ].metalness = 0.2;

  materials[
    "avatar.mat"
  ].roughness = 0.5;


  /* =========================================
     ARMATURE
  ========================================= */

  const [
    armature,
    setArmature,
  ] =
    useState<
      Object3D | undefined
    >();


  const [
    mixer,
    setMixer,
  ] =
    useState<
      AnimationMixer | undefined
    >();


  /* =========================================
     ANIMATION
  ========================================= */

  const actions =
    useRef<
      GLTFActions | undefined
    >();


  const previousAction =
    useRef<ActionName>(
      animation
    );


  const fadeToAction = (
    name: ActionName,
    fadeDuration = 0.2
  ) => {

    const acts =
      actions.current;


    if (!acts) {
      return;
    }


    if (
      name ===
      previousAction.current
    ) {
      return;
    }


    const previous =
      acts[
        previousAction.current
      ];


    if (
      previous &&
      previous.enabled
    ) {

      previous.fadeOut(
        fadeDuration
      );

    }


    const next =
      acts[name];


    if (!next) {
      return;
    }


    next
      .reset()
      .setEffectiveTimeScale(1)
      .setEffectiveWeight(1)
      .fadeIn(
        fadeDuration
      )
      .play();


    previousAction.current =
      name;
  };


  /* =========================================
     LOAD ARMATURE + ACTIONS
  ========================================= */

  useLayoutEffect(() => {

    if (!nodes) {
      return;
    }


    const newArmature =
      SkeletonUtils.clone(
        nodes.Armature
      ) as Object3D;


    const newMixer =
      new THREE.AnimationMixer(
        newArmature
      );


    newArmature.traverse(
      (obj) => {
        obj.frustumCulled =
          false;
      }
    );


    const loadedActions =
      animations.reduce(
        (
          acc,
          cur
        ) => {

          const name =
            cur.name as ActionName;


          acc[name] =
            newMixer.clipAction(
              cur,
              newArmature
            );


          return acc;

        },
        {} as GLTFActions
      );


    actions.current =
      loadedActions;


    const initialAction =
      loadedActions[
        animation
      ];


    if (initialAction) {
      initialAction.play();
    }


    setArmature(
      newArmature
    );

    setMixer(
      newMixer
    );

  }, [nodes]);


  /* =========================================
     ANIMATION CHANGES
  ========================================= */

  useEffect(() => {

    if (
      !armature ||
      !actions.current
    ) {
      return;
    }


    fadeToAction(
      animation,
      duration
    );

  }, [
    animation,
    duration,
    armature,
  ]);


  /* =========================================
     ANIMATION LOOP
  ========================================= */

  useFrame(
    (_, delta) => {

      if (mixer) {
        mixer.update(delta);
      }

    }
  );


  /* =========================================
     RENDER
  ========================================= */

  return (
    <group {...rest}>

      <mesh
        position-y={0.5}
        name="hitbox"
        material={
          materials[
            "avatar.mat"
          ]
        }
        visible={false}
      >

        <boxGeometry
          args={[
            0.35,
            1,
            0.35,
          ]}
        />

      </mesh>


      <group
        name="Armature"
        scale={0.615}
        frustumCulled={false}
      >

        {armature && (
          <primitive
            object={armature}
          />
        )}

      </group>

    </group>
  );
}


useGLTF.preload(
  FILE_URL
);